### PR TITLE
add release-plan to simplify releases

### PR DESCRIPTION
**Pull request by mansona**
I ran `npm init release-plan-setup@latest` to create this PR

This adds release-plan which is a super easy way to get npm releases done. I noticed that there were a few people asking for something to be released in https://github.com/lupomontero/psl/issues/315 so I thought I would provide a solution rather than adding to the chorus of people 👍

### CODE REVIEW

**Comment by punit1108** [comment]
Is this repo active?

**Comment by lupomontero** [comment]
Hi @mansona, many thanks for suggeting this and apologies for the delay in getting back to you. I struggled to maintain this repo for quite a while due to work and personal issues, but I'm now back and two new releases have been published in the last couple of weeks.

I'm doing a lot of house keeping :house::broom: (issues, PRs, ...) as well as _modernising_ the tooling.

I'm not familiar with `release-plan` but will look at it soon, as well as alternatives, to help streamline releases.

**Comment by lupomontero** [comment]
cc/ @mfdebian

**Comment by mansona** [comment]
let me know if you have any questions about it :) really i was just trying to help the process of the release along so feel free to ignore this PR now that things are back moving again.

And to be honest, looking at your git history, I'm not too sure release-plan is the best tool for you 🤔 It really relies on Github PRs to get information about what is in a release and if I'm not mistaken you're doing a rebase-merge for github PRs? So the fact that there is not a merge commit for each PR might prevent you from using release-plan 😞

**Comment by lupomontero** [comment]
In the short term I will be focusing on automating rules updates. Once that has taken shape, and based on how things are progressing, I'll reconsider ways of streamlining the release process. Many thanks for the proposal.

Closing this for the time being.

**Pull request closed without merging**
