### PR TITLE
Add Rules Export

### PR DESCRIPTION
**Pull request by JAD3N**
Fixes: #328 

Changes:
* Added the rules export to the typings.
* Exported the rules.

### CODE REVIEW

**Comment by lupomontero** [comment]
Hi @JAD3N, many thanks for the PRs. Am away from the keyboard right now, but will review this later on today or tomorrow.

**Comment by lupomontero** [comment]
Sorry to keep you waiting with this PR... the thing is that before _exporting_ the rules directly as part of the API as suggested in this PR, I'd first like to complete #334 as there could be changes to the `rules` data type (from `Array` to `Map`) and such a change would mean a _breaking change_ if this had already been merged first since the public API would be affected.

The other PR is being reviewed at the moment and should be merged in the next couple of days :crossed_fingers:

**Comment by JAD3N** [comment]
@lupomontero I'm going to rebase this tomorrow, do you think the mapped rules should be exposed or just the base rules from the `rules.js` file?

**Comment by lupomontero** [comment]
Hi @JAD3N, for the time being I prefer only exposing the `rules` array. The `Map` could change as it is more of an optimization than a public API... 

I'm wondering whether we should also add a _named_ export for the rules. Something like:

```js
export { default as rules } from './data/rules.js';
```

This on top of your proposed change of adding the rulesto the `default` export.

```js
export default { parse, get, isValid, rules };
```

**Comment by JAD3N** [comment]
@lupomontero I've applied the changes mentioned, I also double checked to ensure the build doesn't duplicate anything and it all looks good.

**Review by lupomontero — APPROVED** [review]
LGTM :star:

**Pull request merged**
