### PR TITLE
chore(deps): Replaces deprecated Punycode provided by Node with punycode.js

### PR DESCRIPTION
**Pull request by lupomontero**
Node's [`Punycode`](https://nodejs.org/api/punycode.html) module has been deprecated for years as pointed out by @Macil in #296.

This PR replaces the deprecated module with [mathiasbynens/punycode.js](https://github.com/mathiasbynens/punycode.js) as suggested.

### CODE REVIEW

**Comment by gboer** [comment]
any idea when this can be merged? Would be nice to not have the deprecation warning anymore after this is in :)

**Comment by brycefranzen** [comment]
When will this be merged?

**Comment by SimenB** [comment]
@lupomontero `punycode` is runtime deprecated in the upcoming Node v21, printing a noisy deprecation warning. Do you think you can land this and release a patch? 🙂

**Comment by dmitryplatonov** [comment]
Node v21 is released, and it's complaining about deprecated punycode module. Can this be merged?

**Comment by MikeMcC399** [comment]
@lupomontero 

Are you planning to release a new version now?

[v1.9.0](https://github.com/lupomontero/psl/releases/tag/v1.9.0) is still the latest release.

**Comment by ravanscafi** [comment]
@lupomontero any chance you could tag this new version? we are still getting the old one, so merging the PR didn't help to solve the problem completely.

thank you!

**Comment by alexharpin** [comment]
@lupomontero It looks like this didn't get published as it's still showing 1.9.0 as the latest release.  Any chance of getting this published, especially as you've already done the work on resolving it?

**Comment by mohd-akram** [comment]
Any update on a release with this fix?

**Comment by michaelrommel** [comment]
Please update the npm release!

**Comment by ljharb** [comment]
To be clear, this is a breaking change, because punycode.js v2 doesn't support the same engines as this package (namely, all of them).

If it's changed to v1, it'll be a patch.

**Pull request merged**
