### PR TITLE
Add TypeScript description of API

### PR DESCRIPTION
**Pull request by ntninja**
Hi! I've been using your library for a while and I've recently started to use the TypeScript type checker for my project and noticed that your library has no description and quickly wrote one that gets the job done (both UMD and browser should work, but I only tested the later).

If you're interested in this please make a new release that includes this file and push it to NPM so that the introspection and typing features offered by TypeScript will start to just work for people using that. If not, then feel free to just turn down this PR. I won't be offended or anything. 🙂

### CODE REVIEW

**Comment by lupomontero** [comment]
Hi @alexander255,

Many thanks for the PR 👍 

I'm not (yet) familiar with TypeScript, so I'm not sure how to add a test for this or even if it would be needed... 😊

Would we also need to add a `types` property in the `package.json` file? Something like:

```json
"types": "./psl.d.ts"
```

Can you please provide instructions on how to use/test this for a complete TS noob?

I'd be more than happy to accept the contribution, but would like to understand it first 🐵

Best,

L

**Comment by alexander255** [comment]
Sorry for the late reply! I've been updating the TypeScript file based on the recommendations [here](https://github.com/Microsoft/dtslint/blob/master/README.md) and [here](https://www.typescriptlang.org/docs/handbook/modules.html).

> Would we also need to add a types property in the package.json file?

Indeed, and this has been added now.

> Can you please provide instructions on how to use/test this for a complete TS noob?

You should be able to simply create a new JS project, add `psl` as a dependency in `package.json` and then add a `index.ts` that references the package using ES6 imports (`import * as psl from "psl";`) and use the API as usual. You can then transpile the TS to JS using the `tsc` command.
IMHO the real benefits of using TypeScript over JavaScript are mostly when using an IDE/TextEditor with auto-completion or when working on really large codebases. A 50 line JS snippet really doesn't need TypeScript at all.

> I'd be more than happy to accept the contribution, but would like to understand it first

Understandable!

The unit test fail btw, because `dtslint` requires Node 6.10.x or higher. Do you know what to do about that.

**Comment by alexander255** [comment]
ad testing: Currently the automated tests only check whether the `.d.ts` file is syntactically valid, but not whether it actually matches what is provided by the library its supposed to wrap. Unfortunately, there doesn't seem to be any good tooling for this, so the only real way of verifying this appears to be to write a regular unit test using typescript, transpile it with `tsc` and then let it run against the JavaScript library. Not ideal, but should work.

**Comment by lpellegr** [comment]
Any progress?

**Comment by lupomontero** [comment]
Hi @ntninja :wave: First of all, many thanks for sending this PR and apologies for the delay in getting back to you... I know it's been 6 years... :see_no_evil: ... but I'm finally getting to review this (with the kind help of @mfdebian), so expect news soon :wink:

**Comment by lupomontero** [comment]
Hi again @ntninja. We just merged this into `main` :tada: The PR was so old and outdated that we had to rebase and merge locally to get it in: https://github.com/lupomontero/psl/commit/84aa7d5d158a388bcd094fce11a117697a219779

Many thanks for the contribution :muscle: :raised_hands:

**Pull request closed without merging**
