### PR TITLE
feat: various improvements

### LINKED ISSUE #5: Automate List Updates
It would be ideal if we used the atom feed to update to refresh the official list and run new tests.  I'm not sure if you would want it to automatically push to the repository or package mangers, but it would be good if the delta between updates was minimized.

### LINKED ISSUE #31: Add support for ES6 browser import
It seems the library cannot be loaded with module imports on modern browsers.

The purpose would be to allow such imports since JavaScript imports are now available with all major browsers. Including an esm file or adapting existing files in the NPM package to have a default or another export would allow something like the following:

```
import psl from 'psl';
```

It would also be nice to be able to import only the desired function:

```
import {parse} from 'psl';
```

### LINKED ISSUE #249: platform.sh should be a valid domain
Version 1.8.0

**Steps to reproduce**
`psl.isValid('platform.sh')`

**Expected Behavior**
`true`

**Actual Behavior**
`false`

**Why?**
`platform.sh` is not a TLD while `.sh` is.

### PR DESCRIPTION
**Pull request by favna**
This introduces various improvements that should make things for this package better.

- Changed from Travis to Github Actions
- Improved the TLD auto update script
- Added dependabot config for updating github actions
- Moved source file to src directory
- Replaced uglifyjs + browserify with rollup, which does all of this, plus better (through Terser)
- Changed from npmignore to files array in package.json
- Listed all exports in the package.json, this will ensure that people using ESM will automatically get the proper version, and browser bundlers know to grab the umd bundle.

**Important Note**: Due to the way that GitHub actions work you'll have to add a secret with is a Personal Access Token to create the automatic PRs with in the future.
You can see how to create a PAT here: https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token.
Then once you have that add it to repo secrets as described here: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository
The secret should be named `CI_TOKEN`

fixes #31
fixes #249
resolves #5

### CODE REVIEW

**Comment by kyranet** [comment]
Note: this would also fix #31, as rollup is producing ESM output.

**Review by Nytelife26 — CHANGES_REQUESTED** [review]
LGTM aside from this small change.

**Comment by Favna** [comment]
Bump @lupomontero

**Comment by favna** [comment]
Closing this because repo owner completely ignored this PR and caused many conflicts in the branch that I do not feel like fixing as we have also moved on from using psl in our project.

A true shame considering the amount of issues this was set to fix but I guess @lupomontero just doesn't care.

**Pull request closed without merging**
